name = "shop"
main = "src/worker.js"
compatibility_date = "2026-08-29"

[vars]
TOSS_CLIENT_KEY = "test_ck_D5GePWvyJnrK0W0k6q8gLzN97Eoq"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "shop-db"
database_id = "420da05b-0b17-4a2c-a7da-8e695bee2a11"
migrations_dir = "./migrations"
